draw_set_alpha(1)
draw_set_color(c_white)
draw_set_font(font_debug)
draw_set_halign(fa_left)
//draw_text_transformed(100, 100, "global.current_level: "+string(global.current_level)+"\nglobal.current_event: "+string(global.current_event)+"\nglobal.can_create_new_event: "+string(global.can_create_new_event)+"\nglobal.interactables: "+string(global.interactables)+"\nlevel_properties: "+string(level_properties)+"\nglobal.current_event_interactable: "+string(global.current_event_interactable), 1, 1, 0)